name: gh-checklist
description: Detect and update checkboxes in PR description
author: Ahmed Abdelbaset

branding:
  icon: check-square
  color: blue

inputs:
  token:
    description: GitHub token
    required: true
  template:
    description: |
      PR description template to append when no checkboxes are found in the PR description.
      Leave this field empty to disable the feature.
    required: false
  default:
    description: checked by default comma-seperated
    required: false

outputs:
  checked:
    description: Checked checkboxes
  unchecked:
    description: Unchecked checkboxes

runs:
  using: node16
  main: dist/index.js
